appname = api_Crud_Contenido
httpport = ${API_CRUD_CONTENIDO_HTTP_PORT}
runmode = ${API_CRUD_CONTENIDO_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

PGuser=${API_CRUD_CONTENIDO_PGUSER}
PGpass=${API_CRUD_CONTENIDO_PGPASS}
PGhost=${API_CRUD_CONTENIDO_PGHOST}
PGport=${API_CRUD_CONTENIDO_PGPORT}
PGdb=${API_CRUD_CONTENIDO_PGDB}
PGschema=${API_CRUD_CONTENIDO_PGSCHEMA}

