appname = api_crud_reportes
httpport = ${API_CRUD_REPORTES_HTTP_PORT}
runmode = ${API_CRUD_REPORTES_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

PGuser=${API_CRUD_REPORTES_PGUSER}
PGpass=${API_CRUD_REPORTES_PGPASS}
PGhost=${API_CRUD_REPORTES_PGHOST}
PGport=${API_CRUD_REPORTES_PGPORT}
PGdb=${API_CRUD_REPORTES_PGDB}
PGschema=${API_CRUD_REPORTES_PGSCHEMA}

