appname = api_Crud_Veterinaria
httpport = ${API_CRUD_VETERINARIA_HTTP_PORT}
runmode = ${API_CRUD_VETERINARIA_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

PGuser = ${API_CRUD_VETERINARIA_PGUSER}
PGpass = ${API_CRUD_VETERINARIA_PGPASS}
PGhost = ${API_CRUD_VETERINARIA_PGHOST}
PGport = ${API_CRUD_VETERINARIA_PGPORT}
PGdb = ${API_CRUD_VETERINARIA_PGDB}
PGsschema = ${API_CRUD_VETERINARIA_PGSSCHEMA}