appname = api_Crud_agropecuario
httpport = ${API_CRUD_AGROPECUARIO_HTTP_PORT}
runmode = ${API_CRUD_AGROPECUARIO_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

PGuser = ${API_CRUD_AGROPECUARIO_PGUSER}
PGpass = ${API_CRUD_AGROPECUARIO_PGPASS}
PGhost = ${API_CRUD_AGROPECUARIO_PGHOST}
PGport = ${API_CRUD_AGROPECUARIO_PGPORT}
PGdb = ${API_CRUD_AGROPECUARIO_PGDB}
PGschema = ${API_CRUD_AGROPECUARIO_PGSCHEMA}
