appname = api_Crud_usuarios
httpport = ${API_CRUD_USUARIOS_HTTP_PORT}
runmode = ${API_CRUD_USUARIOS_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

PGuser = ${API_CRUD_USUARIOS_PGUSER}
PGpass = ${API_CRUD_USUARIOS_PGPASS}
PGhost = ${API_CRUD_USUARIOS_PGHOST}
PGport = ${API_CRUD_USUARIOS_PGPORT}
PGdb = ${API_CRUD_USUARIOS_PGDB}
PGschema = ${API_CRUD_USUARIOS_PGSCHEMA}
