appname = api_crud_soporte
httpport = ${API_CRUD_SOPORTE_HTTP_PORT}
runmode = ${API_CRUD_SOPORTE_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

PGuser=${API_CRUD_SOPORTE_PGUSER}
PGpass=${API_CRUD_SOPORTE_PGPASS}
PGhost=${API_CRUD_SOPORTE_PGHOST}
PGport=${API_CRUD_SOPORTE_PGPORT}
PGdb=${API_CRUD_SOPORTE_PGDB}
PGschema=${API_CRUD_SOPORTE_PGSCHEMA}